### ISSUE TITLE
Navegação no iPhone não está funcionando

### ISSUE THREAD

**Issue by Wfelipe2011** [Jwfelipee/next_territory_manager#3]
Quando tento utilizar o ícone de navegação no aplicativo, nada acontece no dispositivo iPhone. No entanto, vale destacar que a funcionalidade está operando normalmente em dispositivos Android.

Passos para reproduzir o problema:
- Abra o aplicativo no iPhone.
- Acesse a pagina de ruas
- Tente clicar no ícone de navegação.

Observe que a navegação não responde como esperado.
Comportamento esperado:
Ao clicar no ícone de navegação, o aplicativo deveria iniciar a função de navegação.

Informações adicionais:

Versão do aplicativo: Alfa 0.1

**Comment by Jwfelipee** [comment]
quando diz navegação, quer dizer abrir o maps e iniciar uma rota de navegação?

**Comment by Wfelipe2011** [comment]
Correção na PR #7
